on:
  push:
  workflow_dispatch:

name: rhel.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#  cancel-in-progress: true

permissions: read-all

jobs:
  rhel:
    runs-on: ubuntu-24.04${{matrix.arch=='arm64' && '-arm' || ''}}
    name: ${{ matrix.os }} ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'rhel8', 'rhel9' ]
        arch: [ 'amd64', 'arm64' ]

    container:
      image: ghcr.io/r-hub/containers/${{ matrix.os }}:latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-hub/actions/register-redhat@main
        env:
          REDHAT_ORG: ${{ secrets.REDHAT_ORG }}
          REDHAT_KEY: ${{ secrets.REDHAT_KEY }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: '"--no-manual"'
        env:
          NOT_CRAN: false
          _R_CHECK_DOC_SIZES_: FALSE
          LANG: en_US.UTF-8
