on:
  push:
  workflow_dispatch:

name: rhel.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#  cancel-in-progress: true

permissions: read-all

jobs:
  rhel:
    runs-on: ubuntu-latest
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          # cannot run the nodejs actions because RHEL7 cannot run node20
          # - { os: rhel7, r: release, key: REDHAT_ACTIVATION_KEY_RHEL7 }
          - { os: rhel8, r: release }
          - { os: rhel9, r: release }
    container:
      image: ghcr.io/r-hub/containers/${{ matrix.config.os }}:latest

    steps:
      - uses: actions/checkout@v4

      - name: Register
        run: |
          subscription-manager register \
            --org ${{ secrets.REDHAT_ORG }} \
            --activationkey ${{ secrets.REDHAT_KEY }}
        shell: bash

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Unregister
        if: always()
        run: |
          subscription-manager unregister || true

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: '"--no-manual"'
        env:
          NOT_CRAN: true
          _R_CHECK_DOC_SIZES_: FALSE
          LANG: en_US.UTF-8
